# EDA Framework

For future datasets, remember this sequence:

**Understand → Validate → Clean → Describe → Visualize → Compare → Investigate → Explain → Recommend**

A data analyst should not stop at *"sales decreased."* Continue asking:

**Where? → When? → Which segment/product/customer? → What variables are associated with it? → Is it an anomaly or recurring pattern? → What should the business investigate or do next?**

## Step 1 — Import libraries

In [2]:
import pandas as pd
import plotly.express as px

## Step 2 — Load the dataset

In [17]:
df = pd.read_csv("listings.csv")


**Ask:** What does one row represent? How many records and columns do we have?

In [18]:
df.shape

(22708, 90)

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 22708 entries, 0 to 22707
Data columns (total 90 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            22708 non-null  int64
 1   listing_url                                   22708 non-null  str
 2   scrape_id                                     22708 non-null  int64
 3   last_scraped                                  22708 non-null  str
 4   source                                        22708 non-null  str
 5   name                                          22708 non-null  str
 6   description                                   21823 non-null  str
 7   neighborhood_overview                         0 non-null      float64
 8   picture_url                                   22707 non-null  str
 9   host_id                                       22708 non-null  int64
 10  host_url                                      22708 non-null  str
 11  host_profile_id                               22556 non-null  float64
 12  host_profile_url                              22556 non-null  str
 13  host_name                                     22556 non-null  str
 14  host_since                                    0 non-null      float64
 15  hosts_time_as_user_years                      22556 non-null  float64
 16  hosts_time_as_user_months                     22556 non-null  float64
 17  hosts_time_as_host_years                      22556 non-null  float64
 18  hosts_time_as_host_months                     22556 non-null  float64
 19  host_location                                 15223 non-null  str
 20  host_about                                    11727 non-null  str
 21  host_response_time                            0 non-null      float64
 22  host_response_rate                            0 non-null      float64
 23  host_acceptance_rate                          0 non-null      float64
 24  host_is_superhost                             22556 non-null  str
 25  host_thumbnail_url                            0 non-null      float64
 26  host_picture_url                              22556 non-null  str
 27  host_neighbourhood                            0 non-null      float64
 28  host_listings_count                           22556 non-null  float64
 29  host_total_listings_count                     0 non-null      float64
 30  host_verifications                            0 non-null      float64
 31  host_has_profile_pic                          22556 non-null  str
 32  host_identity_verified                        22556 non-null  str
 33  neighbourhood                                 0 non-null      float64
 34  neighbourhood_cleansed                        22708 non-null  str
 35  neighbourhood_group_cleansed                  22708 non-null  str
 36  latitude                                      22708 non-null  float64
 37  longitude                                     22708 non-null  float64
 38  property_type                                 22708 non-null  str
 39  room_type                                     22708 non-null  str
 40  accommodates                                  22708 non-null  int64
 41  bathrooms                                     17303 non-null  float64
 42  bathrooms_text                                22688 non-null  str
 43  bedrooms                                      16989 non-null  float64
 44  beds                                          18164 non-null  float64
 45  amenities                                     22708 non-null  str
 46  price                                         19172 non-null  str
 47  price_quote_checkin_date                      19554 non-null  str
 48  price_quote_checkout_date                     19554 non-null  str
 49  price_quote_total_price                       19172 non-null  float64
 50  price_quote_price_per_night                   19172 non-null  float64
 51  price_quote_raw                               19554 non-null  str
 52  minimum_nights                                22706 non-null  float64
 53  maximum_nights                                22706 non-null  float64
 54  minimum_minimum_nights                        22706 non-null  float64
 55  maximum_minimum_nights                        22706 non-null  float64
 56  minimum_maximum_nights                        22706 non-null  float64
 57  maximum_maximum_nights                        22706 non-null  float64
 58  minimum_nights_avg_ntm                        22708 non-null  float64
 59  maximum_nights_avg_ntm                        22708 non-null  float64
 60  calendar_updated                              0 non-null      float64
 61  has_availability                              22626 non-null  str
 62  availability_30                               22708 non-null  int64
 63  availability_60                               22708 non-null  int64
 64  availability_90                               22708 non-null  int64
 65  availability_365                              22708 non-null  int64
 66  calendar_last_scraped                         22708 non-null  str
 67  number_of_reviews                             22708 non-null  int64
 68  number_of_reviews_ltm                         22708 non-null  int64
 69  number_of_reviews_l30d                        22708 non-null  int64
 70  availability_eoy                              22708 non-null  int64
 71  number_of_reviews_ly                          22708 non-null  int64
 72  estimated_occupancy_l365d                     22708 non-null  int64
 73  estimated_revenue_l365d                       19172 non-null  float64
 74  first_review                                  18993 non-null  str
 75  last_review                                   18993 non-null  str
 76  review_scores_rating                          18993 non-null  float64
 77  review_scores_accuracy                        18992 non-null  float64
 78  review_scores_cleanliness                     18992 non-null  float64
 79  review_scores_checkin                         18992 non-null  float64
 80  review_scores_communication                   18992 non-null  float64
 81  review_scores_location                        18991 non-null  float64
 82  review_scores_value                           18990 non-null  float64
 83  license                                       14652 non-null  str
 84  instant_bookable                              0 non-null      float64
 85  calculated_host_listings_count                22708 non-null  int64
 86  calculated_host_listings_count_entire_homes   22708 non-null  int64
 87  calculated_host_listings_count_private_rooms  22708 non-null  int64
 88  calculated_host_listings_count_shared_rooms   22708 non-null  int64
 89  reviews_per_month                             18993 non-null  float64
dtypes: float64(42), int64(18), str(30)
memory usage: 15.6 MB

## Step 3 — Understand structure and data types

**Ask:** Are numeric fields numeric? Is the date actually stored as a date?

In [20]:
# No, No
cols_to_drop = df.columns[[1,7,8,12,14,20,21,22,23,25,26,27,29,30,33,50,51,60,84]]
df.drop(columns= cols_to_drop, inplace= True)

**Convert** data to proper type

In [21]:
df['price'] = df['price'].replace(r'[\$,]','', regex=True).astype(float)

In [22]:
df['price'].dtypes
df.sample(5)

,id,scrape_id,last_scraped,source,name,description,host_id,host_url,host_profile_id,host_name,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
19753,750251,20260620164952,2026-06-21,city scrape,Apartasol Apartamentos Dana,The whole group will enjoy easy access to ever...,130907,https://www.airbnb.com/users/show/130907,1.462510e+18,Dana,...,4.92,4.83,5.00,4.92,Spain - National registration number<br />ESHF...,17,17,0,0,1.04
16228,34958704,20260620164952,2026-06-20,city scrape,Beautiful house across the river !,Hi!<br /><br />The neighborhood is called Puer...,22616098,https://www.airbnb.com/users/show/22616098,1.463184e+18,Judicaël,...,4.92,4.97,4.82,4.68,NaN,1,1,0,0,0.73
9402,1534616630641847204,20260620164952,2026-06-21,city scrape,"Casa moderna, luminosa y acogedora en el centro",In front of the house where Pablo Picasso live...,675836478,https://www.airbnb.com/users/show/675836478,1.470692e+18,Víctor,...,4.88,5.00,4.75,4.79,Spain - National registration number<br />Exem...,3,3,0,0,6.23
5596,9959387,20260620164952,2026-06-21,city scrape,1-8.Las Cortes.Sol.Madrid Center. 70m2.Bright....,"70m2 Apart.,WIFI, A/C, Heater, 2 Bedrooms. 2 X...",51176570,https://www.airbnb.com/users/show/51176570,1.465795e+18,Mar,...,4.91,4.89,4.97,4.76,Madrid - Regional registration number<br />VT-...,6,6,0,0,5.36
2804,1132597898018669090,20260620164952,2026-06-21,city scrape,AyZ Princesa Double Standard room private Bath...,Comfortable room with a memory foam bed and pr...,23441165,https://www.airbnb.com/users/show/23441165,1.462625e+18,AyZ Hotels,...,4.10,3.93,4.56,4.00,Spain - National registration number<br />Exem...,24,0,21,0,2.77

## Step 4 — Check missing values

**Ask:** Which columns have missing values, and what percentage is missing?

In [40]:
df.isnull().mean().sort_values(ascending=False)

license                                         0.354765
host_location                                   0.329620
bedrooms                                        0.251850
bathrooms                                       0.238022
beds                                            0.200106
                                                  ...
maximum_nights_avg_ntm                          0.000000
calculated_host_listings_count                  0.000000
calculated_host_listings_count_entire_homes     0.000000
calculated_host_listings_count_private_rooms    0.000000
calculated_host_listings_count_shared_rooms     0.000000
Length: 71, dtype: float64

## Step 5 — Check duplicates and uniqueness

**Ask:** Are there duplicated rows?

In [ ]:
df.duplicated().sum()
# there is no duplicated rows

np.int64(0)

## Step 6 — Clean obvious data-quality issues

For practice, we will:
- remove exact duplicate rows;
- fill missing categorical values with `"Unknown"`;

In [53]:
# there is no duplicated rows

df.select_dtypes(include= "string")

,last_scraped,source,name,description,host_url,host_name,host_location,host_is_superhost,host_has_profile_pic,host_identity_verified,...,room_type,bathrooms_text,amenities,price_quote_checkin_date,price_quote_checkout_date,has_availability,calendar_last_scraped,first_review,last_review,license
0,2026-06-20,city scrape,Alojamiento tranquilo,You'll be in a family and quiet atmosphere.,https://www.airbnb.com/users/show/509530871,Sandra,NaN,f,f,t,...,Private room,1 bath,"[""Wifi"", ""Refrigerator"", ""Kitchen""]",2026-06-21,2026-06-22,t,2026-06-20,NaN,NaN,NaN
1,2026-06-20,city scrape,Hermoso para disfrutar Madrid,Enjoy the simplicity of this quiet and central...,https://www.airbnb.com/users/show/425181129,Felix,"Madrid, Spain",f,t,t,...,Entire home/apt,1 bath,"[""Wifi"", ""Fire extinguisher"", ""Refrigerator"", ...",2026-06-21,2026-06-22,t,2026-06-20,2023-05-14,2023-05-14,NaN
2,2026-07-02,previous scrape,"Bright & comfortable, Malasana Madrid","The appartment is very well located, very cent...",https://www.airbnb.com/users/show/43556711,Anthony,"Beirut, Lebanon",f,t,t,...,Entire home/apt,1 bath,"[""Kitchen"", ""Washer"", ""Essentials"", ""Wifi"", ""S...",NaN,NaN,t,2026-07-02,2017-12-09,2018-01-18,NaN
3,2026-07-01,previous scrape,"H10 Puerta de Alcalá 4 Sup, Classic Room",NaN,https://www.airbnb.com/users/show/726634087,NaN,NaN,NaN,NaN,NaN,...,Private room,1 private bath,"[""Fire extinguisher"", ""Hangers"", ""Bed linens"",...",NaN,NaN,f,2026-07-01,2026-03-01,2026-03-01,NaN
4,2026-07-01,previous scrape,Double standard room I Akeah Gran Vía,NaN,https://www.airbnb.com/users/show/726323161,NaN,NaN,NaN,NaN,NaN,...,Private room,1 private bath,"[""Fire extinguisher"", ""Hangers"", ""Bed linens"",...",2026-07-09,2026-07-10,f,2026-07-01,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22703,2026-07-02,previous scrape,Studio with balcony,NaN,https://www.airbnb.com/users/show/739050243,NaN,NaN,NaN,NaN,NaN,...,Private room,1 private bath,"[""Hangers"", ""Bed linens"", ""Gym"", ""Hot water"", ...",2026-07-02,2026-07-03,f,2026-07-02,2026-02-20,2026-06-15,NaN
22704,2026-07-02,previous scrape,Two bedroom apartment with view,NaN,https://www.airbnb.com/users/show/739050243,NaN,NaN,NaN,NaN,NaN,...,Private room,1 private bath,"[""Hangers"", ""Bed linens"", ""Gym"", ""Hot water"", ...",2026-07-02,2026-07-03,f,2026-07-02,2026-02-17,2026-06-14,NaN
22705,2026-07-02,previous scrape,Two bedroom apartment,NaN,https://www.airbnb.com/users/show/739050243,NaN,NaN,NaN,NaN,NaN,...,Private room,1 private bath,"[""Hangers"", ""Bed linens"", ""Gym"", ""Hot water"", ...",2026-07-02,2026-07-03,f,2026-07-02,2026-02-20,2026-06-16,NaN
22706,2026-07-02,previous scrape,One bedroom superior apartment,NaN,https://www.airbnb.com/users/show/739050243,NaN,NaN,NaN,NaN,NaN,...,Private room,1 private bath,"[""Hangers"", ""Bed linens"", ""Gym"", ""Hot water"", ...",2026-07-02,2026-07-03,f,2026-07-02,2026-02-15,2026-06-07,NaN
22707,2026-07-02,previous scrape,Superior Studio,NaN,https://www.airbnb.com/users/show/739050243,NaN,NaN,NaN,NaN,NaN,...,Private room,1 private bath,"[""Hangers"", ""Bed linens"", ""Gym"", ""Hot water"", ...",2026-07-02,2026-07-03,f,2026-07-02,2026-02-01,2026-06-08,NaN

## Step 7 — Descriptive statistics

**Ask:** What are the typical values, ranges, and variability?

## Step 8 — Explore categorical variables

**Ask:** What are the most common segments, regions, categories, and shipping modes?

In [ ]:
categorical_cols = df.select_dtypes(include='object')

**Visualize** the categorical columns

In [ ]:

for col in categorical_cols:

    value_counts = (
        df[col]
        .value_counts()
        .head(12)
        .reset_index()
    )

    value_counts.columns = [col, "Count"]

    fig = px.bar(
        value_counts,
        x=col,
        y="Count",
        text_auto=True,
        title=f"{col.title()} - Frequency Distribution"
    )

    fig.show()

## Step 9 — Explore numerical distributions

Histograms help identify skewness, concentration, and unusual values.

In [ ]:
numbers=df.select_dtypes(include=['number'])

**Visualize** the numerical columns

In [ ]:
for col in numbers:

    fig = px.histogram(df,x=col,
        nbins=30,
        title=f"Distribution of {col.title()}",
        labels={
            col: col.title(),
            "count": "Frequency"
        })

    fig.show()

## Step 10 — Detect outliers using IQR

The common IQR rule defines potential outliers as values below:

`Q1 - 1.5 × IQR`

or above:

`Q3 + 1.5 × IQR`

### Visualize outliers with a box plot

In [ ]:
for col in numbers:
    fig = px.box(
        df,
        y=col,
        title=f"Box Plot: {col.title()}"
    )

    fig.show()

## Step 11 — Analyze relationships between numerical variables

**Ask:** use correlation

In [ ]:
fig = px.scatter_matrix(
    df,
    dimensions=numbers,
    title="Scatter Matrix of Numeric Variables"
)

fig.show()

## Step 12 — Compare performance across groups

**Ask:** use Groupby

## Step 13 — Time-series EDA

**Ask:** what is trend over time? Are some months stronger than others?

## Step 14 — Find the best and worst performers

A useful EDA habit is to inspect both extremes rather than only averages.

## Step 15 — Business questions

Try answering these from the analysis above:

1. Which region generates the highest sales?
2. Which region generates the highest profit?
3. Which category generates the highest sales?
4. Which category is most profitable?
5. Does higher discount appear to reduce profitability?
6. Which orders are unusually large?
7. Are high-sales orders always high-profit orders?
8. Which month has the highest sales?
9. Which customer segment contributes the most revenue?
10. What data-quality issues did we discover?