<img src="../assets/ga-logo.png" style="float: left; margin: 20px; height: 55px">

# Regression Metrics - Solution

> All models are wrong, but some are useful.
>
> - <cite>George EP Box</cite>

### About
An introduction to Regression Metrics: what they are, how they work, and how use them to assess regression models in `scikit-learn`.

### Learning Objectives
- Describe the principles of regression metrics.
- Define common metrics including error measures (MAE, MSE, RMSE), R2, Adj R2 and others.
- Apply regression metrics to assess OLS models.


### Notebook Guide

- Metric #1 (Warmup): Euclidean Distance
- Prologue: Let's fit a model!
- Metric #2: Sum Squared Error (SSE)
- Metric #3: Mean Squared Error (MSE)
- Metric #4: The Coefficient of Determination (R2)
- Metric #5: Mean Absolute Deviation
- Conclusion and Takeaways

# Imports
As always... come back to this cell when you want to add more imports!

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn import metrics

# Metric #1 (Warmup): Euclidean Distance

In [2]:
y = [4, 18, 9, 2, 7, 5]
y_hat = [3, 15, 8, 1, 8, 12]

In [3]:
# Compute the distance via a listcomp!
np.sqrt(sum([(yi - y_hati)**2 for yi, y_hati in zip(y, y_hat)]))

np.float64(7.874007874011811)

In [4]:
# Compute the distance via numpy!
y = np.array(y)
y_hat = np.array(y_hat)

np.sqrt(np.sum((y - y_hat)**2))

np.float64(7.874007874011811)

# Prologue: Let's fit a model!

In [5]:
# Read in ad data
ads = pd.read_csv('../data/Advertising.csv')
ads.head()

   Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [6]:
# (THREAD) Drop unnamed col
ads.drop(columns='Unnamed: 0', inplace=True)

### Think
Look at this data. What do you think is a good question to ask that we might model?

### Quick EDA
Let's poke around this data to see what we're working with.

In [7]:
ads.dtypes

TV           float64
radio        float64
newspaper    float64
sales        float64
dtype: object

In [8]:
ads.describe()

               TV       radio   newspaper       sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   14.022500
std     85.854236   14.846809   21.778621    5.217457
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   10.375000
50%    149.750000   22.900000   25.750000   12.900000
75%    218.825000   36.525000   45.100000   17.400000
max    296.400000   49.600000  114.000000   27.000000

In [9]:
ads.isna().sum()

TV           0
radio        0
newspaper    0
sales        0
dtype: int64

In [10]:
# Create the design matrix (X) and response vector (y)
X = ads.drop(columns='sales')
y = ads.sales

In [11]:
# Fit a linear regression model
lm = LinearRegression()
lm.fit(X, y)

LinearRegression()

In [12]:
# Create a prediction vector y_hat
y_hat = lm.predict(X)

In [13]:
lm.coef_

array([ 0.04576465,  0.18853002, -0.00103749])

In [14]:
# Interpret one of the slopes for me!
# For a one-unit increase in radio advertising, we expect sales to increase by $0.19M.

# Metric #2: Sum Squared Error (SSE)

In [15]:
# Compute the SSE using numpy
sse = np.sum((y - y_hat)**2)
sse

np.float64(556.8252629021872)

# Metric #3: Mean Squared Error (MSE)

In [16]:
# Compute the MSE using numpy
mse = np.mean((y - y_hat)**2)
mse

np.float64(2.784126314510936)

In [17]:
# Compute the MSE using sklearn!
metrics.mean_squared_error(y, y_hat)

2.784126314510936

### Metric #3.5: The Root Mean Squared Error (RMSE)

In [18]:
# Compute the RMSE! Does it make sense?
np.sqrt(metrics.mean_squared_error(y, y_hat))

np.float64(1.6685701407225697)

# Metric #4: The Coefficient of Determination ($R^2$)

In [19]:
# Let's compute it "by hand"
sse = np.sum((y - y_hat)**2)
ssto = np.sum((y - np.mean(y))**2)
1 - sse / ssto

np.float64(0.8972106381789522)

In [20]:
# Can also compute directly via sklearn!
lm.score(X, y)

0.8972106381789522

In [21]:
# ...and via metrics
metrics.r2_score(y, y_hat)

0.8972106381789522

In [22]:
# Let's compute the SSE, MSE, RMSE of the null model.
m = y.mean()
sse = np.sum((y - m)**2)
mse = np.mean((y - m)**2)
rmse = np.sqrt(mse)

print(f"SSE = {sse}")
print(f"MSE = {mse}")
print(f"RMSE = {rmse}")

SSE = 5417.14875
MSE = 27.085743750000002
RMSE = 5.204396578855228

In [23]:
# Compare to our OLS model:
sse = np.sum((y - y_hat)**2)
mse = metrics.mean_squared_error(y, y_hat)
rmse = np.sqrt(mse)

print(f"SSE = {sse}")
print(f"MSE = {mse}")
print(f"RMSE = {rmse}")

SSE = 556.8252629021872
MSE = 2.784126314510936
RMSE = 1.6685701407225697

# Metric #5: Mean Absolute Deviation

In [24]:
# Compute!
metrics.mean_absolute_error(y, y_hat)

1.2520112296870685

# Conclusion and Takeaways
In this lesson, we:

- Learned what distance metrics are (mathematically) and how they might apply to us
- Learned several regression error metrics, and why/when we might use them
- Explored the `sklearn.metrics` submodule and poked around all the different metrics it provides