## __Data Science: Capstone Part 1: Lightning Talk 1__

### Overview

In the field of data science, good projects are practical. Your capstone project should be manageable and affect a real world audience. This might be a domain you are familiar with, a particular interest you have, something that affects a community you are involved in, or an area that relates to a field you wish to work in.

One of the best ways to test ideas quickly is to share them with others. A good data scientist has to be comfortable discussing ideas and presenting to audiences. That's why for Part 1 of your Capstone project, you'll be preparing a lightning talk on some potential interest areas and datasets.

This deliverable will provide you with guidance to help you select an awesome topic and begin to build a polished Capstone project.

__Goal__: Host a lightning talk presentation describing at least three project proposals, including associated data, problem statement, goals, approach, and basic EDA.

### REQUIRED

__Foreach Topic__:
- Problem Statement
- Goals
- Approach
- Data Source(s)
- Data Info. (basic EDA)

Dataset should have __15k+__ rows and __10+__ columns

___Remember, if you can't find data to support your topic, then you can't move forward.___

# Topic 1 : [Your Title]

## Problem Statement

[your problem statment here]

## Data Info
Data Source :

## Data Dictionary
| Column    | Type    | Description |
| --------  | ------- | -------     |
| Id        | int     | unique identifier |

In [2]:
# start you EDA
import pandas as pd

In [17]:
df = pd.read_csv('../Preventive to Predictive Maintenance/Test_Data_CSV.csv')
df.head()

,Data_No,Differential_pressure,Flow_rate,Time,Dust_feed,Dust,RUL
0,1,0.271267,52.281993,0.1,236.428943,"ISO 12103-1, A3 Medium Test Dust",58.9
1,1,0.361690,54.986671,0.2,236.428943,"ISO 12103-1, A3 Medium Test Dust",58.8
2,1,0.000000,55.424786,0.3,236.428943,"ISO 12103-1, A3 Medium Test Dust",58.7
3,1,2.622251,55.524146,0.4,236.428943,"ISO 12103-1, A3 Medium Test Dust",58.6
4,1,3.888165,55.852018,0.5,236.428943,"ISO 12103-1, A3 Medium Test Dust",58.5

In [18]:
df.shape

(39414, 7)

In [1]:
# What is your target column and what does it represent?
# Is your target categorical or continuous? is it balanced (Plot the distribution)?
# What types of features do you have (categorical / numerical)? how many of each ?
# How many null values does each feature have?
# Which features are most correlated with your target, and with each other?
# Are there outliers?

# Topic 2 : [Your Title]

## Problem Statement

[your problem statment here]

## Data Info
Data Source :

## Data Dictionary
| Column    | Type    | Description |
| --------  | ------- | -------     |
| Id        | int     | unique identifier |

In [5]:
df2 = pd.read_csv('../Microsoft Azure Predictive Maintenance/PdM_errors.csv')
df2.head()

              datetime  machineID errorID
0  2015-01-03 07:00:00          1  error1
1  2015-01-03 20:00:00          1  error3
2  2015-01-04 06:00:00          1  error5
3  2015-01-10 15:00:00          1  error4
4  2015-01-22 10:00:00          1  error4

In [6]:
df2 = pd.read_csv('../Microsoft Azure Predictive Maintenance/PdM_failures.csv')
df2.head()

              datetime  machineID failure
0  2015-01-05 06:00:00          1   comp4
1  2015-03-06 06:00:00          1   comp1
2  2015-04-20 06:00:00          1   comp2
3  2015-06-19 06:00:00          1   comp4
4  2015-09-02 06:00:00          1   comp4

In [7]:
df2 = pd.read_csv('../Microsoft Azure Predictive Maintenance/PdM_machines.csv')
df2.head()

   machineID   model  age
0          1  model3   18
1          2  model4    7
2          3  model3    8
3          4  model3    7
4          5  model3    2

In [8]:
df2 = pd.read_csv('../Microsoft Azure Predictive Maintenance/PdM_maint.csv')
df2.head()

              datetime  machineID   comp
0  2014-06-01 06:00:00          1  comp2
1  2014-07-16 06:00:00          1  comp4
2  2014-07-31 06:00:00          1  comp3
3  2014-12-13 06:00:00          1  comp1
4  2015-01-05 06:00:00          1  comp4

In [11]:
df2 = pd.read_csv('../Microsoft Azure Predictive Maintenance/PdM_telemetry.csv')
df2.head()
df2.shape

(876100, 6)

In [ ]:
# What is your target column and what does it represent?
# Is your target categorical or continuous? is it balanced (Plot the distribution)?
# What types of features do you have (categorical / numerical)? how many of each ?
# How many null values does each feature have?
# Which features are most correlated with your target, and with each other?
# Are there outliers?

# Topic 3 : [Your Title]

## Problem Statement

[your problem statment here]

## Data Info
Data Source :

## Data Dictionary
| Column    | Type    | Description |
| --------  | ------- | -------     |
| Id        | int     | unique identifier |

In [ ]:
df3 = pd.read_csv('')
df3.head()

In [ ]:
# What is your target column and what does it represent?
# Is your target categorical or continuous? is it balanced (Plot the distribution)?
# What types of features do you have (categorical / numerical)? how many of each ?
# How many null values does each feature have?
# Which features are most correlated with your target, and with each other?
# Are there outliers?